name: Polars and Pandas Script CI

# Este workflow se ejecuta en cada push a la rama main
on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Chequea el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Configura Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Paso 3: Instala las dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install polars pandas

      # Paso 4: Ejecuta el script
      - name: Run script
        run: python script.py
