name: Print Git Log

on:
  schedule:
    - cron: '25 17 * * 1,3'  # Ejecutar a las 17:25 (UTC-5) los lunes y miércoles

jobs:
    git_log:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v3
        - name: Show Git Log
          run: git log
    
      pull_request:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v3