name: Prueba 1

on:
  push:
    paths:
      - 'tareas/Reyes_Carla/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: |
        docker build -t githubactions tareas/Reyes_Carla

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Tag Docker Image
      run: docker tag githubactions ${{ secrets.DOCKERHUB_USERNAME }}/githubactions:latest

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/githubactions:latest

    - name: Run Docker Container
      run: docker run ${{ secrets.DOCKERHUB_USERNAME }}/githubactions > output.log

    - name: Print Docker Output
      run: cat output.log
