name: actions

on:
  push:
    branches:
      - main
    paths:
      - 'tareas/Uria_Jaime/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Build Docker image
        run: |
          docker build -t DOCKER_USERNAME/${{ github.repository }}:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push DOCKER_USERNAME/${{ github.repository }}:${{ github.sha }}
          continue-on-error: true

      - name: Print Docker Output
        run: |
          cat output.log
          continue-on-error: true
