name: Action_dockerhub

on:
  pull_request:
  push:
    paths:
      - 'tareas/Uria_Jaime/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build docker image
      run: docker build -t actions/Jaime
    - name: Dockerhub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push Docker Image to Docker Hub
      run: |
        docker tag gitact_hw ${{ secrets.DOCKERHUB_USERNAME }}/gitact_hw:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/gitact_hw:latest
    - name: Run Docker Container
      run: |
        docker run ${{ secrets.DOCKERHUB_USERNAME }}/gitact_hw > output.log
