name: Action_dockerhub

on:
  pull_request:
  push:
    paths:
      - 'tareas/Uria_Jaime/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/jaime-app:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/jaime-app:latest

    - name: Run Docker Container
      run: docker run ${{ secrets.DOCKERHUB_USERNAME }}/jaime-app > output.log
