name: GitActions

on:
  pull_request:
  push:
    paths:
      - 'tareas/Varela_Lu/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -t tarea tareas/Varela_Lu

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      - name: Tag Docker Image
        run: docker tag tarea "${DOCKER_USERNAME}/tarea:latest"

      - name: Push Docker Image to Docker Hub
        run: docker push "${DOCKER_USERNAME}/tarea:latest"

      - name: Run Docker Container and print output
        run: |
          docker run "${DOCKER_USERNAME}/tarea:latest" > output.log
          cat output.log
