ame: GitActions

on:
  pull_request:
  push:
    paths:
      - 'tareas/LuciaVarela/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -t tarea tareas/LuciaVarela

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - name: Tag Docker Image
        run: docker tag tarea ${{ secrets.DOCKERHUB_USERNAME }}/tarea:latest

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tarea:latest

      - name: Run Docker Container and print output
        run: |
          docker run ${{ secrets.DOCKERHUB_USERNAME }}/tarea > output.log
          cat output.log
